
[api]
host = "127.0.0.1"
port = 8000
secret_key = ""

[database]
host = "localhost"
port = 5432
username = "virtualpaper"
password = "very-secret-password"
database = "virtualpaper"

[processing]
input_dir = "input"
tmp_dir = "/tmp"
output_dir = "media"
max_workers = 4
