# Virtualpaper configuration file


# http api
[api]
# host & port to bind
host = "127.0.0.1"
port = 8000
# secret key, a new one is created if key is empty. Don't expose it.
secret_key = ""
# If you need to define cors hosts, put all hosts here.
cors_hosts = []
# Public facing url, for creating urls for clients
public_url = "http://localhost:8000"
# serve web page from this directory. Leave empty to serve only api and not web page.
static_content_path= "static"
# Token expire time in seconds. Set to 0 to disable. Default value is 1 week.
token_expire_sec = 579600


# Database, only postgres is supported.
[database]
host = "localhost"
port = 5432
username = "virtualpaper"
password = "very-secret-password"
database = "virtualpaper"
no_ssl = false


# Meilisearch search-engine. A new meilisearch-index is created for each user-id.
[meilisearch]
apikey = ""
url = "http://localhost:7700"
# index. Virtualpaper will create one index for each user, this will be suffix for all indices. Indices are
# named as virtualpaper-<user_id>
index = "virtualpaper"



# Processing / application data.
[processing]
input_dir = "input"
tmp_dir = "/tmp"
# output directory is where all documents / data is persisted.
output_dir = "media"
# Max background workers allowed. If empty, set to number of cpus available.
max_workers = 4

# array of tesseract languages. Each language requires separate tesseract-data package to be installed.
ocr_languages = ["eng"]

# to use pdftotext binary for faster and more reliable pdf parsing, set binary path.
pdftotext_bin = ""

pandoc_bin = ""

# Mail configuration. Uncomment to enable setings mails.
# Host must be smtp server that is accessible with authentication.
# Mail uses TLS if available. Auth is of type PLAIN.
#[mail]

# Smpt host and port.
#host = ""
#port = 587

# smpt plain text authentication
#username = "smptuser"
#password = "smtppasswd"

# From-field in emails
#from = "virtualpaper@demo"

# Default error recipient. Uncomment to send errors via mail.
#error_recipient = "foo@bar.com"


# Logging configuration
[logging]
# Loglevel, valid levels: trace,debug,info,warning,error,fatal,panic
log_level = "INFO"
# Directory for log files
directory = "log"
# Log http requests to stdout
log_http_stdout = true
# Http log file, no http logs if file name is empty
http_log_file = "http.log"
# Application log file
log_file = "virtualpaper.log"
# Log all logs to stdout in, helpful for interactive mode / development
log_stdout = true

